// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 19/09/2025 17:05:01
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Applications/MAMP/htdocs/msia/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/msia/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/msia/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/msia/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/msia/app/plugins/**/*.{js,ts,mjs}","/Applications/MAMP/htdocs/msia/app/composables/**/*.{js,ts,mjs}","/Applications/MAMP/htdocs/msia/app/utils/**/*.{js,ts,mjs}","/Applications/MAMP/htdocs/msia/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/msia/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/msia/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;